namespace CRISP.Core.Common
{
    /// <summary>
    /// Provides a base implementation for all domain models in the system.
    /// </summary>
    /// <remarks>
    /// This abstract record serves as the foundation for all domain entities,
    /// providing a consistent unique identifier property. Using a record type
    /// ensures immutability and provides value-based equality semantics,
    /// which are important for domain modeling and event sourcing scenarios.
    /// </remarks>
    public abstract record BaseModel
    {
        /// <summary>
        /// Gets the unique identifier for the model.
        /// </summary>
        /// <value>
        /// An integer representing the unique identifier of the entity.
        /// This property is typically auto-generated by the persistence layer
        /// and serves as the primary key for database operations.
        /// </value>
        public Guid Id { get; init; }
    }

    /// <summary>
    /// Provides a base implementation for domain models that require audit tracking.
    /// </summary>
    /// <remarks>
    /// This abstract record extends <see cref="BaseModel"/> with audit-related properties
    /// that track creation time, last update time, and archival status. These properties
    /// are essential for maintaining data lineage, compliance requirements, and implementing
    /// soft delete patterns through archival rather than permanent deletion.
    /// </remarks>
    public abstract record BaseAuditableModel : BaseModel
    {
        /// <summary>
        /// Gets the date and time when the model was created.
        /// </summary>
        /// <value>
        /// A <see cref="DateTime"/> value in UTC representing when the entity was first created.
        /// This property is automatically initialized to <see cref="DateTime.UtcNow"/> when
        /// the entity is instantiated, providing an automatic audit trail of creation times.
        /// </value>
        public DateTime CreatedOn { get; init; } = DateTime.UtcNow;

        /// <summary>
        /// Gets the date and time when the model was last updated.
        /// </summary>
        /// <value>
        /// A <see cref="DateTime"/> value in UTC representing when the entity was last modified.
        /// This property is automatically initialized to <see cref="DateTime.UtcNow"/> when
        /// the entity is instantiated and should be updated whenever the entity is modified.
        /// </value>
        public DateTime UpdatedOn { get; init; } = DateTime.UtcNow;

        /// <summary>
        /// Gets a value indicating whether the model is archived (soft deleted).
        /// </summary>
        /// <value>
        /// A boolean value indicating the archival status of the entity.
        /// When <c>true</c>, the entity is considered archived and should be excluded
        /// from normal business operations while being preserved for audit and compliance purposes.
        /// The default value is <c>false</c>, indicating an active entity.
        /// </value>
        public bool IsArchived { get; init; }
    }
}
