namespace Crisp;

/// <summary>
/// RFC 7807 Problem Details for HTTP APIs
/// </summary>
public record ProblemDetails
{
    /// <summary>
    /// A URI reference [RFC3986] that identifies the problem type.
    /// </summary>
    public string? Type { get; init; }
    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    public string? Title { get; init; }
    /// <summary>
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    /// </summary>
    public int? Status { get; init; }
    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string? Detail { get; init; }
    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// </summary>
    public string? Instance { get; init; }
    /// <summary>
    /// A collection of additional key-value pairs to provide extra context about the problem.
    /// </summary>
    public Dictionary<string, object?> Extensions { get; init; } = [];
}
