name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for complete history if needed
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
    
    - name: Verify project structure
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "Solution projects:"
        dotnet sln list
        echo "Checking Crisp.Core project:"
        ls -la src/Crisp.Core/
    
    - name: Restore dependencies
      run: dotnet restore Crisp.sln --verbosity normal
    
    - name: Build
      run: dotnet build Crisp.sln --configuration Release --no-restore --verbosity normal
    
    - name: Test
      run: dotnet test Crisp.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory ./TestResults
      
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Tests
        path: 'TestResults/*.trx'
        reporter: dotnet-trx
        fail-on-error: false
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        files: '**/coverage.cobertura.xml'