name: Release to NuGet

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
    
    - name: Debug .NET installation
      run: |
        echo "=== .NET Info ==="
        dotnet --info
        echo "=== Available runtimes ==="
        dotnet --list-runtimes
        echo "=== Available SDKs ==="
        dotnet --list-sdks
        echo "=== Environment ==="
        echo "DOTNET_ROOT: $DOTNET_ROOT"
        echo "PATH: $PATH"
        ls -la /usr/share/dotnet/shared/Microsoft.NETCore.App/ || echo "Directory not found"
    
    - name: Restore dependencies
      run: dotnet restore Crisp.sln --verbosity normal
    
    - name: Build
      run: dotnet build Crisp.sln --configuration Release --no-restore --verbosity normal
    
    - name: Test
      run: dotnet test Crisp.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory ./TestResults
    
    - name: Set Version from Release Tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        
    - name: Package Crisp.Core
      run: dotnet pack src/Crisp.Core/Crisp.Core.csproj --configuration Release --no-build --output ./packages /p:Version=${{ env.VERSION }} /p:PackageId=Crisp.Core

    - name: Package Crisp.AspNetCore
      run: dotnet pack src/Crisp.AspNetCore/Crisp.AspNetCore.csproj --configuration Release --no-build --output ./packages /p:Version=${{ env.VERSION }} /p:PackageId=Crisp.AspNetCore
    
    - name: Push to NuGet Crisp.Core
      run: dotnet nuget push ./packages/Crisp.Core.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Push to NuGet Crisp.AspNetCore
      run: dotnet nuget push ./packages/Crisp.AspNetCore.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate